environment      = "dev"
folder_id        = "b1g7q85lgictgf4j1dq8"
pg_cluster_id    = "c9q1384cb8tqrg09o8n4"
pg_database_name = "web-app-db-dev"
pg_user_name     = "burcev-dev"
sa_name          = "burcev-dev"
